
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: gcr.io/diesel-post-453122-r2/hello-world-app:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
